name: "boton"
description: "Realiza revision de codigo basandose en modelos LLMs, aunque por ahora no hace nada -es solo un boton-"
author: "Alguien misterioso"

inputs:
  llm_provider:
    description: "Proveedor de LLM a utilizar."
    required: true
    default: "azure_openai"
  llm_endpoint:
    description: "Endpoint para la API del LLM"
    required: true
  llm_api_key:
    description: "API key para el servicio de LLM"
    required: true
  github_token:
    description: "El token de github para poder postear comentarios"
    required: true
  prompt_file:
    description: "Archivo que contiene los prompts a utilizar en la corrida. Default: .github/prompts.yml"
    required: false
    default: ".configs/prompts.yml"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    LLM_PROVIDER: ${{ inputs.llm_provider }}
    LLM_ENDPOINT: ${{ inputs.llm_endpoint }}
    LLM_API_KEY: ${{ inputs.llm_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PROMPT_FILE: ${{ inputs.prompt_file }}